# 配置服务器信息
server:
  port: 6617
  servlet:
    context-path: /labi

# 数据库
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # 此处为非正确格式。正确格式仅用于自测，不正式提交
    url: jdbc:postgresql://202.99.114.60:3700/ampdb
    data-username: postgres
    data-password: xxx

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 500000  #不小于30s 否则会回到默认的1800秒
      connection-timeout: 30000
      connection-test-query: SELECT 1
